name: CI + Security Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2️⃣ Setup Java
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Build & Test
      - name: Build with Maven
        run: mvn clean test

      # 4️⃣ GITLEAKS – Secret Scanning
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      # 5️⃣ OWASP Dependency Check
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "github-actions-demo"
          path: "."
          format: "HTML"
          out: "dependency-check-report"
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      # 6️⃣ Upload OWASP Report
      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-report
          path: dependency-check-report
